## $\Large{Numpy\; 練習題}$

In [1]:
import numpy as np

---
# 1-Dimension Array

## Exercise 1
使用np.arrange 函數創建一個數值從10到49的一維陣列

In [2]:
np.arange(10,49,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

## Exercise 2
請建立一個陣列，裡頭包含0~101中所有完全平方數(ex. 1, 4, 9...)

In [3]:
index = 101
a = []
for i in range (index) :
    if np.sqrt(i) % 1 == 0 :
        a.append(i)

print(a)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


## Exercise 3
反轉陣列x使得陣列內的元素從尾排到頭

In [4]:
x = np.array([2, 0, 3, 1, 4, 7])

In [5]:
x[::-1]  # 從頭到尾 間隔-1取值

array([7, 4, 1, 3, 0, 2])

## Exercise 4
將x陣列內數值介於3到8(包含3和8)的元素取負號

In [6]:
X = np.array([6, 2, 8, 3, 0, 1])

In [7]:
mask = (3 <= X) & (X <= 8)
X[mask] = -X[mask]
X

array([-6,  2, -8, -3,  0,  1])

## Exercise 5
創建一個長度為10的隨機數字陣列，並且將最大值取代為0

In [8]:
test = np.random.randn(10)
print(test)
test[np.argmax(test)]=0
print(test)

[-0.56655545  1.61302771 -1.12666116 -0.59666947 -0.22641519 -0.56792773
  0.76640307  0.55373811 -1.58085856 -1.12653662]
[-0.56655545  0.         -1.12666116 -0.59666947 -0.22641519 -0.56792773
  0.76640307  0.55373811 -1.58085856 -1.12653662]


## Exercise 6
從陣列x中取出符合以下條件的子集

(1) 不能被 3 整除

(2) 可以被 3 整除

(3) 可以被 3 或 5 整除

In [9]:
x = np.array([3, 4, 6, 10, 24, 89, 45, 43, 46, 99, 100])

In [10]:
mask1 = (x % 3) != 0
mask2 = (x % 3) == 0
mask3 = ((x % 3) == 0), ((x % 5) == 0).any()

display(x[mask1])
display(x[mask2])
display(x[mask3])

array([  4,  10,  89,  43,  46, 100])

array([ 3,  6, 24, 45, 99])

array([ 3,  6, 24, 45, 99])

## Exercise 7
使用np.arange建立從2019年1月到12月共12個月的陣列資料

範例結果如下
<img src='./Slides_image/ex7_pic.PNG'/>

In [11]:
np.arange('2019-01', '2019-12', dtype='datetime64[M]')

array(['2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06',
       '2019-07', '2019-08', '2019-09', '2019-10', '2019-11'],
      dtype='datetime64[M]')

---
# n-Dimension Array

## Exercise 8
請以ndim與shape兩個用法印出陣列x的維度數目與各維度的長度

In [12]:
x = np.array([[[[[[[[[[[[[[[[[5, 4, 3, 2, 1]]]], [[[[10, 9, 8, 7, 6]]]]]]]]]]]]]]]]])

In [13]:
print(x.ndim)
print(x.shape)

17
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 5)


## Exercise 9
使用np.random.random 函數創建一個3x3x3的陣列

In [14]:
np.random.random((3,3,3))

array([[[0.18854799, 0.06613973, 0.77536356],
        [0.62142351, 0.97552871, 0.40682069],
        [0.05296429, 0.60767796, 0.66709411]],

       [[0.34362179, 0.71760036, 0.74622723],
        [0.21974357, 0.01064574, 0.52245267],
        [0.44619973, 0.31023733, 0.85494276]],

       [[0.59826442, 0.56324978, 0.84896281],
        [0.69191029, 0.59238638, 0.789795  ],
        [0.13178751, 0.67147178, 0.01334871]]])

## Exercise 10
創建一個5x5且數值介於0到4之間的整數陣列

In [15]:
np.random.randint(0,5,(5,5))

array([[4, 0, 1, 2, 4],
       [4, 4, 0, 4, 0],
       [4, 4, 4, 0, 1],
       [2, 4, 1, 1, 4],
       [3, 1, 2, 0, 2]])

## Exercise 11
創建一個擁有隨機數值且形狀為10x10的陣列，並且使用np.min 和 np.max兩函數找出陣列中的最大值/最小值

In [16]:
test = np.random.random((10,10))
print("test = ", test)
print("min = ", np.min(test))
print("Max = ", np.max(test))

test =  [[0.6111914  0.69068615 0.28690911 0.41811557 0.32664971 0.85337343
  0.86309325 0.93219324 0.77736246 0.79777097]
 [0.7935985  0.33198153 0.01009474 0.69673659 0.65385715 0.05251221
  0.47865974 0.92730351 0.34718328 0.53782372]
 [0.47086932 0.30258693 0.37512221 0.30660738 0.46903972 0.88121005
  0.90292588 0.97666101 0.34385661 0.76692425]
 [0.03470891 0.24812585 0.58767843 0.10175774 0.4004249  0.8668306
  0.13777832 0.89934808 0.00815485 0.0335373 ]
 [0.43532531 0.01859278 0.51196614 0.20214347 0.63630049 0.3866224
  0.97924115 0.4101818  0.20790745 0.36433495]
 [0.98506858 0.70228087 0.56403986 0.84163346 0.09123633 0.936432
  0.23933002 0.82019026 0.52879602 0.72711887]
 [0.99773553 0.08310434 0.54027776 0.60010997 0.25216235 0.05190429
  0.58892803 0.4405156  0.60089041 0.13014159]
 [0.5126596  0.44992157 0.11670041 0.11595861 0.52046436 0.02534382
  0.20391102 0.10870806 0.23738202 0.40939826]
 [0.61367047 0.36901118 0.75535023 0.77130991 0.06732019 0.03068239
  0.8502

## Exercise 12
使用reshape函數將陣列x轉成最後一個維度的長度為1且第一個維度為3的3維陣列

In [17]:
x = np.arange(9)

In [18]:
y = x.reshape((3,-1,1))
print(y)
print(y.shape)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
(3, 3, 1)


## Exercise 13
請針對x陣列中的每欄資料做累積加總

註：加總後的陣列數值將為 [[2, 6, 3], [7, 15, 4]]

In [19]:
x = np.array([2, 6, 3, 5, 9, 1]).reshape(2, -1)

In [20]:
print(x)
y = np.sum(x, 0)
print(y)

[[2 6 3]
 [5 9 1]]
[ 7 15  4]


## Exercise 14
陣列標準化: 將x陣列內所有的元素除以x陣列內元素的最大值

In [21]:
x = np.random.randn(6).reshape(2, 3)

In [22]:
print(x)
print("norm = ", x/np.max(x))

[[-1.09497135 -0.0591038   0.30382415]
 [-0.1370255  -0.43417701  1.38354742]]
norm =  [[-0.79142307 -0.04271903  0.21959793]
 [-0.09903925 -0.31381433  1.        ]]


## Exercise 15
請計算出x陣列中相鄰數字的差異並同樣存成np.array型態

註：由於x陣列有6個數字，因此相鄰數字的差異共會有5個數值，依序為 [-151, 224, -158, -88, 572]

In [23]:
x = np.array([183, 32, 256, 98, 10, 582])

In [24]:
dif = []
for i in range(len(x)-1) :
    dif.append(x[i+1]-x[i])
np.array(dif)

array([-151,  224, -158,  -88,  572])

## Exercise 16
請將x陣列中所有數值可被3整除的元素索引列出

註：由於x為二維陣列，單一個元素的索引會有兩個數字(ex.[1, 0])

In [25]:
x = np.arange(20).reshape(4, 5)

In [26]:
print(x)
row,col = np.where(x % 3 ==0)
for i in range(len(row)) :
    print("x[%g][%g]" %(row[i],col[i]),"is what you want")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x[0][0] is what you want
x[0][3] is what you want
x[1][1] is what you want
x[1][4] is what you want
x[2][2] is what you want
x[3][0] is what you want
x[3][3] is what you want


## Exercise 17
使用np.pad 函數在陣列x外圍加一層0，使得原本3x3的陣列變為5x5

In [27]:
x = np.ones(shape=(3, 3))

In [28]:
print(x)
print(x.shape)
print(np.pad(x,((1,1),(1,1)),'constant',constant_values = (0,0)))
print(np.pad(x,((1,1),(1,1)),'constant',constant_values = (0,0)).shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)


## Exercise 18
計算x與y兩兩元素的乘積並做加總(答案應為32)

註：上述的做法其實就是矩陣內積，因此有超過兩種以上的作法可以計算出此答案，大家可以試試看自己會幾種

In [29]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [30]:
print(np.sum(np.multiply(x,y)))
print(np.squeeze(np.dot(x,y.T)))

32
32


## Exercise 19
使用np.concatenate函數將陣列x與陣列y合併在一起，使其與```np.append(x, y, axis = 1)```結果相同

In [31]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

print(np.append(x, y, axis=1))

[[1 2 3 4 5 6]]


In [32]:
np.concatenate((x,y),axis=1)

array([[1, 2, 3, 4, 5, 6]])

### 請參考 [100-numpy-exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb) 做更多 numpy 的操作練習